package com.cn.lingrui.sellPersonnel.db.dbpojos;

public class NBPT_SP_PERSON_REGION {

	private String NBPT_SP_PERSON_REGION_UID; // 唯一ID
	private String NBPT_SP_PERSON_REGION_PID; // 人员唯一ID
	private String NBPT_SP_PERSON_REGION_RID; // 部门唯一ID
	private String NBPT_SP_PERSON_REGION_TYPE; // 对应类型
	public String getNBPT_SP_PERSON_REGION_UID() {
		return NBPT_SP_PERSON_REGION_UID;
	}
	public void setNBPT_SP_PERSON_REGION_UID(String nBPT_SP_PERSON_REGION_UID) {
		NBPT_SP_PERSON_REGION_UID = nBPT_SP_PERSON_REGION_UID;
	}
	public String getNBPT_SP_PERSON_REGION_PID() {
		return NBPT_SP_PERSON_REGION_PID;
	}
	public void setNBPT_SP_PERSON_REGION_PID(String nBPT_SP_PERSON_REGION_PID) {
		NBPT_SP_PERSON_REGION_PID = nBPT_SP_PERSON_REGION_PID;
	}
	public String getNBPT_SP_PERSON_REGION_RID() {
		return NBPT_SP_PERSON_REGION_RID;
	}
	public void setNBPT_SP_PERSON_REGION_RID(String nBPT_SP_PERSON_REGION_RID) {
		NBPT_SP_PERSON_REGION_RID = nBPT_SP_PERSON_REGION_RID;
	}
	public String getNBPT_SP_PERSON_REGION_TYPE() {
		return NBPT_SP_PERSON_REGION_TYPE;
	}
	public void setNBPT_SP_PERSON_REGION_TYPE(String nBPT_SP_PERSON_REGION_TYPE) {
		NBPT_SP_PERSON_REGION_TYPE = nBPT_SP_PERSON_REGION_TYPE;
	}
	
}
