package com.cn.lingrui.sellPersonnel.db.dbpojos;

public class NBPT_VIEW_REGION {
	
	private String NBPT_SP_REGION_UID;
	private String NBPT_SP_REGION_ID;
	private String NBPT_SP_REGION_NAME;
	private String NBPT_SP_REGION_NEED;
	private String NBPT_SP_REGION_RESPONSIBLER;
	private String NBPT_SP_REGION_RESPONSIBLER_JOB;
	private String NBPT_SP_REGION_LEVEL;
	private String NBPT_SP_REGION_NOTE;
	private String NBPT_SP_REGION_PARENT_UID;
	private String NBPT_SP_REGION_PARENT_ID;
	private String NBPT_SP_REGION_PARENT_NAME;
	private String NBPT_SP_REGION_PARENT_NEED;
	private String NBPT_SP_REGION_PARENT_RESPONSIBLER;
	private String NBPT_SP_REGION_PARENT_LEVEL;
	private String NBPT_SP_REGION_PARENT_NOTE;
	private String NBPT_SP_REGION_PROVINCE_ID;
	private String NBPT_SP_REGION_PROVINCE_NAME;
	private String NBPT_SP_REGION_RESPONSIBLER_NAME;
	private String NBPT_SP_REGION_PARENT_RESPONSIBLER_NAME;
	public String getNBPT_SP_REGION_UID() {
		return NBPT_SP_REGION_UID;
	}
	public void setNBPT_SP_REGION_UID(String nBPT_SP_REGION_UID) {
		NBPT_SP_REGION_UID = nBPT_SP_REGION_UID;
	}
	public String getNBPT_SP_REGION_ID() {
		return NBPT_SP_REGION_ID;
	}
	public void setNBPT_SP_REGION_ID(String nBPT_SP_REGION_ID) {
		NBPT_SP_REGION_ID = nBPT_SP_REGION_ID;
	}
	public String getNBPT_SP_REGION_NAME() {
		return NBPT_SP_REGION_NAME;
	}
	public void setNBPT_SP_REGION_NAME(String nBPT_SP_REGION_NAME) {
		NBPT_SP_REGION_NAME = nBPT_SP_REGION_NAME;
	}
	public String getNBPT_SP_REGION_RESPONSIBLER() {
		return NBPT_SP_REGION_RESPONSIBLER;
	}
	public void setNBPT_SP_REGION_RESPONSIBLER(String nBPT_SP_REGION_RESPONSIBLER) {
		NBPT_SP_REGION_RESPONSIBLER = nBPT_SP_REGION_RESPONSIBLER;
	}
	public String getNBPT_SP_REGION_LEVEL() {
		return NBPT_SP_REGION_LEVEL;
	}
	public void setNBPT_SP_REGION_LEVEL(String nBPT_SP_REGION_LEVEL) {
		NBPT_SP_REGION_LEVEL = nBPT_SP_REGION_LEVEL;
	}
	public String getNBPT_SP_REGION_NOTE() {
		return NBPT_SP_REGION_NOTE;
	}
	public void setNBPT_SP_REGION_NOTE(String nBPT_SP_REGION_NOTE) {
		NBPT_SP_REGION_NOTE = nBPT_SP_REGION_NOTE;
	}
	public String getNBPT_SP_REGION_PARENT_UID() {
		return NBPT_SP_REGION_PARENT_UID;
	}
	public void setNBPT_SP_REGION_PARENT_UID(String nBPT_SP_REGION_PARENT_UID) {
		NBPT_SP_REGION_PARENT_UID = nBPT_SP_REGION_PARENT_UID;
	}
	public String getNBPT_SP_REGION_PARENT_ID() {
		return NBPT_SP_REGION_PARENT_ID;
	}
	public void setNBPT_SP_REGION_PARENT_ID(String nBPT_SP_REGION_PARENT_ID) {
		NBPT_SP_REGION_PARENT_ID = nBPT_SP_REGION_PARENT_ID;
	}
	public String getNBPT_SP_REGION_PARENT_NAME() {
		return NBPT_SP_REGION_PARENT_NAME;
	}
	public void setNBPT_SP_REGION_PARENT_NAME(String nBPT_SP_REGION_PARENT_NAME) {
		NBPT_SP_REGION_PARENT_NAME = nBPT_SP_REGION_PARENT_NAME;
	}
	public String getNBPT_SP_REGION_PARENT_RESPONSIBLER() {
		return NBPT_SP_REGION_PARENT_RESPONSIBLER;
	}
	public void setNBPT_SP_REGION_PARENT_RESPONSIBLER(String nBPT_SP_REGION_PARENT_RESPONSIBLER) {
		NBPT_SP_REGION_PARENT_RESPONSIBLER = nBPT_SP_REGION_PARENT_RESPONSIBLER;
	}
	public String getNBPT_SP_REGION_PARENT_LEVEL() {
		return NBPT_SP_REGION_PARENT_LEVEL;
	}
	public void setNBPT_SP_REGION_PARENT_LEVEL(String nBPT_SP_REGION_PARENT_LEVEL) {
		NBPT_SP_REGION_PARENT_LEVEL = nBPT_SP_REGION_PARENT_LEVEL;
	}
	public String getNBPT_SP_REGION_PARENT_NOTE() {
		return NBPT_SP_REGION_PARENT_NOTE;
	}
	public void setNBPT_SP_REGION_PARENT_NOTE(String nBPT_SP_REGION_PARENT_NOTE) {
		NBPT_SP_REGION_PARENT_NOTE = nBPT_SP_REGION_PARENT_NOTE;
	}
	public String getNBPT_SP_REGION_PARENT_NEED() {
		return NBPT_SP_REGION_PARENT_NEED;
	}
	public void setNBPT_SP_REGION_PARENT_NEED(String nBPT_SP_REGION_PARENT_NEED) {
		NBPT_SP_REGION_PARENT_NEED = nBPT_SP_REGION_PARENT_NEED;
	}
	public String getNBPT_SP_REGION_NEED() {
		return NBPT_SP_REGION_NEED;
	}
	public void setNBPT_SP_REGION_NEED(String nBPT_SP_REGION_NEED) {
		NBPT_SP_REGION_NEED = nBPT_SP_REGION_NEED;
	}
	public String getNBPT_SP_REGION_PROVINCE_NAME() {
		return NBPT_SP_REGION_PROVINCE_NAME;
	}
	public void setNBPT_SP_REGION_PROVINCE_NAME(String nBPT_SP_REGION_PROVINCE_NAME) {
		NBPT_SP_REGION_PROVINCE_NAME = nBPT_SP_REGION_PROVINCE_NAME;
	}
	public String getNBPT_SP_REGION_PROVINCE_ID() {
		return NBPT_SP_REGION_PROVINCE_ID;
	}
	public void setNBPT_SP_REGION_PROVINCE_ID(String nBPT_SP_REGION_PROVINCE_ID) {
		NBPT_SP_REGION_PROVINCE_ID = nBPT_SP_REGION_PROVINCE_ID;
	}
	public String getNBPT_SP_REGION_RESPONSIBLER_NAME() {
		return NBPT_SP_REGION_RESPONSIBLER_NAME;
	}
	public void setNBPT_SP_REGION_RESPONSIBLER_NAME(String nBPT_SP_REGION_RESPONSIBLER_NAME) {
		NBPT_SP_REGION_RESPONSIBLER_NAME = nBPT_SP_REGION_RESPONSIBLER_NAME;
	}
	public String getNBPT_SP_REGION_PARENT_RESPONSIBLER_NAME() {
		return NBPT_SP_REGION_PARENT_RESPONSIBLER_NAME;
	}
	public void setNBPT_SP_REGION_PARENT_RESPONSIBLER_NAME(String nBPT_SP_REGION_PARENT_RESPONSIBLER_NAME) {
		NBPT_SP_REGION_PARENT_RESPONSIBLER_NAME = nBPT_SP_REGION_PARENT_RESPONSIBLER_NAME;
	}
	public String getNBPT_SP_REGION_RESPONSIBLER_JOB() {
		return NBPT_SP_REGION_RESPONSIBLER_JOB;
	}
	public void setNBPT_SP_REGION_RESPONSIBLER_JOB(String nBPT_SP_REGION_RESPONSIBLER_JOB) {
		NBPT_SP_REGION_RESPONSIBLER_JOB = nBPT_SP_REGION_RESPONSIBLER_JOB;
	}
	
}
