package com.cn.lingrui.sellPersonnel.db.dbpojos;

public class NBPT_SP_REGION_XZQX {

	private String NBPT_SP_REGION_XZQX_UID;
	private String NBPT_SP_REGION_XZQX_REGIONID;
	private String NBPT_SP_REGION_XZQX_REGIONUID;
	private String NBPT_SP_REGION_XZQX_XZQXID;
	private String NBPT_SP_REGION_XZQX_TYPE;
	public String getNBPT_SP_REGION_XZQX_UID() {
		return NBPT_SP_REGION_XZQX_UID;
	}
	public void setNBPT_SP_REGION_XZQX_UID(String nBPT_SP_REGION_XZQX_UID) {
		NBPT_SP_REGION_XZQX_UID = nBPT_SP_REGION_XZQX_UID;
	}
	public String getNBPT_SP_REGION_XZQX_REGIONID() {
		return NBPT_SP_REGION_XZQX_REGIONID;
	}
	public void setNBPT_SP_REGION_XZQX_REGIONID(String nBPT_SP_REGION_XZQX_REGIONID) {
		NBPT_SP_REGION_XZQX_REGIONID = nBPT_SP_REGION_XZQX_REGIONID;
	}
	public String getNBPT_SP_REGION_XZQX_XZQXID() {
		return NBPT_SP_REGION_XZQX_XZQXID;
	}
	public void setNBPT_SP_REGION_XZQX_XZQXID(String nBPT_SP_REGION_XZQX_XZQXID) {
		NBPT_SP_REGION_XZQX_XZQXID = nBPT_SP_REGION_XZQX_XZQXID;
	}
	public String getNBPT_SP_REGION_XZQX_TYPE() {
		return NBPT_SP_REGION_XZQX_TYPE;
	}
	public void setNBPT_SP_REGION_XZQX_TYPE(String nBPT_SP_REGION_XZQX_TYPE) {
		NBPT_SP_REGION_XZQX_TYPE = nBPT_SP_REGION_XZQX_TYPE;
	}
	public String getNBPT_SP_REGION_XZQX_REGIONUID() {
		return NBPT_SP_REGION_XZQX_REGIONUID;
	}
	public void setNBPT_SP_REGION_XZQX_REGIONUID(String nBPT_SP_REGION_XZQX_REGIONUID) {
		NBPT_SP_REGION_XZQX_REGIONUID = nBPT_SP_REGION_XZQX_REGIONUID;
	}
	
	
}
