package com.cn.lingrui.common.db.dbpojos;

public class NBPT_RSFZ_CONDITION {
	
	private String NBPT_RSFZ_CONDITION_TYPE;
	private String NBPT_RSFZ_CONDITION_NAME;
	private String NBPT_RSFZ_CONDITION_ITEM;
	public String getNBPT_RSFZ_CONDITION_TYPE() {
		return NBPT_RSFZ_CONDITION_TYPE;
	}
	public void setNBPT_RSFZ_CONDITION_TYPE(String nBPT_RSFZ_CONDITION_TYPE) {
		NBPT_RSFZ_CONDITION_TYPE = nBPT_RSFZ_CONDITION_TYPE;
	}
	public String getNBPT_RSFZ_CONDITION_NAME() {
		return NBPT_RSFZ_CONDITION_NAME;
	}
	public void setNBPT_RSFZ_CONDITION_NAME(String nBPT_RSFZ_CONDITION_NAME) {
		NBPT_RSFZ_CONDITION_NAME = nBPT_RSFZ_CONDITION_NAME;
	}
	public String getNBPT_RSFZ_CONDITION_ITEM() {
		return NBPT_RSFZ_CONDITION_ITEM;
	}
	public void setNBPT_RSFZ_CONDITION_ITEM(String nBPT_RSFZ_CONDITION_ITEM) {
		NBPT_RSFZ_CONDITION_ITEM = nBPT_RSFZ_CONDITION_ITEM;
	}
	
}
