package com.cn.test;

public class XZQXPOJO {

	private String NBPT_COMMON_XZQXHF_ID;
	private String NBPT_COMMON_XZQXHF_NAME;
	private String NBPT_COMMON_XZQXHF_PID;
	private String NBPT_COMMON_XZQXHF_LEVEL;
	public String getNBPT_COMMON_XZQXHF_ID() {
		return NBPT_COMMON_XZQXHF_ID;
	}
	public void setNBPT_COMMON_XZQXHF_ID(String nBPT_COMMON_XZQXHF_ID) {
		NBPT_COMMON_XZQXHF_ID = nBPT_COMMON_XZQXHF_ID;
	}
	public String getNBPT_COMMON_XZQXHF_NAME() {
		return NBPT_COMMON_XZQXHF_NAME;
	}
	public void setNBPT_COMMON_XZQXHF_NAME(String nBPT_COMMON_XZQXHF_NAME) {
		NBPT_COMMON_XZQXHF_NAME = nBPT_COMMON_XZQXHF_NAME;
	}
	public String getNBPT_COMMON_XZQXHF_PID() {
		return NBPT_COMMON_XZQXHF_PID;
	}
	public void setNBPT_COMMON_XZQXHF_PID(String nBPT_COMMON_XZQXHF_PID) {
		NBPT_COMMON_XZQXHF_PID = nBPT_COMMON_XZQXHF_PID;
	}
	public String getNBPT_COMMON_XZQXHF_LEVEL() {
		return NBPT_COMMON_XZQXHF_LEVEL;
	}
	public void setNBPT_COMMON_XZQXHF_LEVEL(String nBPT_COMMON_XZQXHF_LEVEL) {
		NBPT_COMMON_XZQXHF_LEVEL = nBPT_COMMON_XZQXHF_LEVEL;
	}
	
	
}
